### ISSUE TITLE
work with grails 2.3 or higher

### ISSUE THREAD

**Issue by mgkimsal** [goeh/grails-attachmentable#1]
the configuration stuff has change in 2.3, and this plugin no longer works out of the box.  any plans to update it for grails 2.3/4 and/or/grails 3?

**Comment by goeh** [comment]
I have made the necessary changes for Grails 2.4.x compatibility but the plugin has no tests so I cannot release it yet. I will add some tests tomorrow and release version 0.4.0 if everything goes well.

**Comment by mgkimsal** [comment]
oh nice - thanks!  I used this plugin years ago, and liked it, but was running in to some problems with it today.  I started trying to do a conversion, but then figured I'd just ask.

**Comment by goeh** [comment]
Version 0.4.0 is now published to grails central repo and should be Grails 2.4.x compatible

**Comment by mgkimsal** [comment]
looks good - thanks
